# Save Sampels
ROS:
  image_topic_name: '/camera/image_raw'
  pointcloud_topic_name: '/lidar_points'

Sync:
  threshold: 0.067 # tolerace for synchronization in secs
  img_folder: 'images'
  pcd_folder: 'pcds'
  total_samples: 200 # total number of samples to save
  frame_delay: 2 # delay in frames between samples
  set_delay: 3 # delay between sets in secs
  set_size: 10 # number of samples in one set
